<a href="https://colab.research.google.com/github/gopikrishna7-hash/Data-Science-Implementation/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cwd=os.getcwd()
print(cwd)

/content

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nmnbabbar/house-pricing")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nmnbabbar/house-pricing/1.archive...

100%|██████████| 10.0k/10.0k [00:00<00:00, 6.41MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/nmnbabbar/house-pricing/versions/1

In [ ]:
import os
import pandas as pd
os.listdir(path)
csv_file=os.path.join(path,'house_prices.csv')
df=pd.read_csv(csv_file)
df.head()

   HouseID     Location  Bedrooms  Bathrooms  SquareFeet   Price
0        1      Chicago         1          2        1928  266294
1        2      Chicago         2          1        1093   83082
2        3     New York         3          1        2100  431828
3        4      Chicago         4          2        2456   85311
4        5  Los Angeles         4          2        1524  267251

In [ ]:
cwd=os.getcwd()
print(cwd)

/content

In [ ]:
df.to_csv("/content/house_prices.csv")

In [ ]:
df.duplicated(subset="Location")
df["Location"].value_counts()

Location
New York       280
Los Angeles    254
Chicago        246
Houston        220
Name: count, dtype: int64

In [ ]:
# Handling Missing Values
import numpy as np
df.iloc[2,3]=np.nan

In [ ]:
df.isnull()
df.fillna(df['Bathrooms'].mean())

     HouseID     Location  Bedrooms  Bathrooms  SquareFeet   Price
0          1      Chicago         1   2.000000        1928  266294
1          2      Chicago         2   1.000000        1093   83082
2          3     New York         3   1.525526        2100  431828
3          4      Chicago         4   2.000000        2456   85311
4          5  Los Angeles         4   2.000000        1524  267251
..       ...          ...       ...        ...         ...     ...
995      996     New York         3   2.000000        2528  253692
996      997  Los Angeles         1   2.000000         563  113057
997      998     New York         1   1.000000         793  387508
998      999  Los Angeles         4   2.000000         625   85333
999     1000  Los Angeles         2   1.000000        1834  265544

[1000 rows x 6 columns]

In [ ]:
import numpy as np
df[["Birth_year"]]=np.random.randint(1985,2016,size=(len(df),1))

In [ ]:
current_year=2026
df["Age"]=current_year-df["Birth_year"]
print(df[["Birth_year","Age"]])

     Birth_year  Age
0          2001   25
1          1997   29
2          1989   37
3          1992   34
4          1989   37
..          ...  ...
995        1995   31
996        1995   31
997        2009   17
998        1986   40
999        1997   29

[1000 rows x 2 columns]

In [ ]:
df["Is_Child"]=np.where()

In [ ]:
df["Is_Child"]=np.where(df['Age'] < 18 ,0,1)

In [ ]:
print(df[df["Age"]<18][["Birth_year","Age","Is_Child"]])

     Birth_year  Age  Is_Child
0          2001   25         1
1          1997   29         1
2          1989   37         1
3          1992   34         1
4          1989   37         1
..          ...  ...       ...
991        2000   26         1
995        1995   31         1
996        1995   31         1
998        1986   40         1
999        1997   29         1

[731 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop("Price",axis=1)
Y=df["Price"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(Y_test.shape)
print(Y_train.shape)

(800, 8)
(200, 8)
(200,)
(800,)